Feature: Login API / User State / Auth State / Protected Route / Autologoff
ChildMindInstitute/mindlogger-web-refactor pull request #12
Opened 2022-12-14 07:00 UTC by moiskillnadne

2022-12-15 13:29 UTC, BamMironov requested changes

2022-12-15 13:45 UTC, moiskillnadne commented on .env
> +VITE_API_HOST=/api/v1
Done

2022-12-15 13:53 UTC, moiskillnadne commented on src/app/InactivityTracker.tsx
> +  let timer: NodeJS.Timeout | undefined
Done

2022-12-15 14:04 UTC, moiskillnadne commented on src/app/InactivityTracker.tsx
> +    localStorage.clear()
Done

2022-12-15 14:05 UTC, moiskillnadne commented on src/app/InactivityTracker.tsx
> +  })
Done

2022-12-16 09:32 UTC, moiskillnadne commented on src/app/routes.tsx
> +      {auth?.token && (
Done

2022-12-16 10:00 UTC, moiskillnadne commented on src/entities/user/model/auth.slice.ts
> +      return state
Done

2022-12-16 10:05 UTC, moiskillnadne commented on src/entities/user/model/auth.slice.ts
> +      return state
Done

2022-12-16 10:06 UTC, moiskillnadne commented on src/entities/user/model/user.slice.ts
> +      return state
Done

2022-12-16 10:07 UTC, moiskillnadne commented on src/entities/user/model/interface.ts
> +export type TUserSchema = z.infer<typeof UserSchema>
Done

2022-12-16 10:30 UTC, moiskillnadne commented on src/pages/Login/lib/api.ts
> +  const fetcher = useMutation([name], (data: TLoginForm) => makeRequest(data), options)
It is a common case. Work properly.

2022-12-16 10:43 UTC, moiskillnadne commented on src/pages/Login/ui/index.tsx
> +                disabled={!isObjectEmpty(errors) || mutation.isLoading}
Done

2022-12-16 12:36 UTC, moiskillnadne commented on src/pages/Login/model/types.ts
> +  user: {
Done

2022-12-20 08:57 UTC, merged