[M2-2961]Feature: activity flow passing business logic
ChildMindInstitute/mindlogger-web-refactor pull request #189
Opened 2023-08-14 12:16 UTC by moiskillnadne

2023-08-22 21:02 UTC, BamMironov requested changes

2023-08-23 08:12 UTC, moiskillnadne commented on src/shared/utils/hooks/useEntityType.ts
> +export const useFlowType = (): Return => {
Done

2023-08-23 08:18 UTC, moiskillnadne commented on src/widgets/ActivityDetails/model/hooks/useEntityComplete.ts
> +  const flowCompleted = (flowId: string) => {
Done

2023-08-23 08:36 UTC, moiskillnadne commented on src/widgets/ActivityDetails/model/hooks/useEntityComplete.ts
> +    const currentActivityIndexInFlow = currentFlow.activityIds.findIndex(activityId => activityId === props.activityId)!
Fixed it

2023-08-23 08:50 UTC, moiskillnadne commented on src/widgets/ActivityDetails/model/hooks/useEntityComplete.ts
> +    }
Done

2023-08-23 08:54 UTC, moiskillnadne commented on src/widgets/ActivityDetails/model/hooks/useEntityComplete.ts
> +    )
Done

2023-08-23 09:13 UTC, moiskillnadne commented on src/widgets/ActivityDetails/model/hooks/useEntityComplete.ts
> +    )
Done

2023-08-23 09:14 UTC, moiskillnadne commented on src/widgets/ActivityDetails/ui/AssessmentLayoutHeader.tsx
> +  const onClick = () => {
Done

2023-08-23 10:37 UTC, BamMironov approved these changes

2023-08-23 10:37 UTC, BamMironov commented on src/widgets/ActivityDetails/model/hooks/useAnswers.ts
> +  }, [])
Please unwrap the function from userCallback

2023-08-23 10:38 UTC, merged