[M2-4833] Feature: Additional text response [WIP]
ChildMindInstitute/mindlogger-web-refactor pull request #356
Opened 2024-01-30 05:38 UTC by sultanofcardio

2024-01-31 00:14 UTC, mbanting requested changes
Saw on Slack that this was looking for reviewers but title says WIP. Went ahead and added a few minor comments anyways. Overall it looks great and thank you for the amazing and helpful PR description!

2024-01-31 00:24 UTC, sultanofcardio commented
Thanks for taking a look @mbanting. I forgot to remove the WIP from the title.

I'll address your other comments in the morning. Regarding the TODO, I was supposed to enquire about the user events today to see if it's something I could add here or if it needs support in the API first. I'll ask the question in Slack to see what needs to happen

2024-01-31 13:51 UTC, moiskillnadne requested changes

2024-01-31 16:19 UTC, sultanofcardio commented on src/entities/activity/lib/helpers.ts
> +/**
Good call. I've added the test file

2024-01-31 16:19 UTC, sultanofcardio commented on src/widgets/ActivityDetails/ui/AssessmentPassingScreen.tsx
> +    // TODO: saveSetAdditionalTextUserEvent
I've clarified how these work and implemented the user event

2024-01-31 16:20 UTC, sultanofcardio commented on src/entities/activity/ui/ActivityCardItem.tsx
> +  const additionalTextLabel = requiresAdditionalResponse(item)
Indeed, the logic is backwards. I've switched to using the `isOptional` prop instead

2024-01-31 17:08 UTC, mbanting commented on src/entities/activity/lib/helpers.ts
> +/**
Thank you!

2024-01-31 17:09 UTC, mbanting approved these changes

2024-01-31 17:34 UTC, moiskillnadne requested changes

2024-01-31 17:34 UTC, moiskillnadne commented on src/entities/applet/model/types.ts
> +export type UserEventTypes = "SET_ANSWER" | "SET_ADDITIONAL_TEXT" | "PREV" | "NEXT" | "SKIP" | "DONE"
No need to create a new type. Reuse "SET_ANSWER"

2024-01-31 17:34 UTC, moiskillnadne commented on src/entities/applet/model/hooks/useUserEvents.ts
Here a bit different logic is expected. Basically, additional text changes are not a new event. It extends current events. Let me show some examples:

We have the singleSelect with the additional text.

User choose answer first
The user event will looks like
{
 type: "SET_ANSWER",
 screen: activityItemScreenId,
 time: Date.now(),
 response: item.answer[0],
}

Then, the user fills in additional text, and user event will be updated
{
 type: "SET_ANSWER",
 screen: activityItemScreenId,
 time: Date.now(),
 response: item.answer[0],
 additionalAnswer: "asd"
}

Take into account please that the additional answer has "like text" behavior. So it updates the same event while the user fills in additional text.

And also handle the case when user fills in additional text first and then choose the answer

2024-01-31 17:47 UTC, sultanofcardio commented on src/entities/applet/model/hooks/useUserEvents.ts
Is there any specific reason we want to reuse the `SET_ANSWER` event instead of creating a new one? I briefly contemplated doing that, but I didn't have a reason to lean either way and I'd like to understand the reasoning

2024-01-31 21:13 UTC, farmerpaul approved these changes
Great PR @sultanofcardio, love the clear commit-by-commit breakdown. Tested the flow with various activity/item configurations and it works as expected. I just had a couple very minor code-related questions.

2024-02-01 02:01 UTC, sultanofcardio commented on src/entities/activity/ui/AdditionalTextResponse.tsx
> +    }
This is just an opportunity for simplification that I missed. I created this component from `TextItem` without realising I could've just removed the `onHandleValueChange` function entirely.

https://github.com/ChildMindInstitute/mindlogger-web-refactor/blob/93112d554d1535353a3796af1d058677e0225e91/src/entities/activity/ui/items/Text.tsx#L13-L33

Thanks for pointing this out 👍

2024-02-01 02:06 UTC, sultanofcardio commented on src/entities/applet/model/slice.ts
> +      }
We're in the same boat here. I don't think I'm any more familiar with Redux than you are. As I understand, it should always return state but given that there are other reducers doing this I just copied an existing one to remain consistent. Maybe a larger question that could be considered in a separate ticket

2024-02-01 18:34 UTC, moiskillnadne commented on src/entities/applet/model/hooks/useUserEvents.ts
Yes, sure. The main reason is the parity between the web application and the mobile application. The mobile app already has the same functionality and has agreements with the admin panel on what event types and DTOs are used for communication.

So I have discussed with @BamMironov  how it was implemented in the mobile app and I think we should implement the feature the same way.

2024-02-01 18:38 UTC, sultanofcardio commented on src/entities/applet/model/hooks/useUserEvents.ts
Ah, that makes sense. Thanks for explaining. I'll take another look at the mobile app for inspiration

2024-02-01 22:39 UTC, sultanofcardio commented on src/entities/applet/model/hooks/useUserEvents.ts
I've made the change but with a slight caveat. The Mobile App stores its user events with the response portion in this shape:

```typescript
export type PipelineItemAnswerBase = {
  type: ActivityItemType;
  value: {
    answer?: PipelineItemResponse;
    additionalAnswer?: string;
  };
};
```

Where `PipelineItemResponse` is one of many types corresponding to the item answers. The web app stores it like this:

```typescript
export type UserEvents = {
  type: UserEventTypes
  time: number
  screen: string
  response?: UserEventResponse
}

export type UserEventResponse =
  | string
  | {
      value: number[]
      text?: string
    }
```

Here `UserEventResponse` is supposed to be the equivalent of `PipelineItemResponse` but it is much less fleshed out. I didn't want to turn this PR into bringing the two types in line with each other, so I made a small update to support additional text on more types besides `singleSelect` and `multiSelect` items.

```typescript
export type UserEventResponse =
  | string
  | {
      value: string | string[] | number[]
      text?: string
    }
```

This is to avoid storing the additional text by itself for those items (like `slider`), because it would look like the user cleared the answer to set the additional text. Let me know if this is a suitable compromise until a wider change can be made

2024-02-02 09:51 UTC, moiskillnadne approved these changes
Looks good to me. Thanks

2024-02-02 10:10 UTC, merged