feat: adds paragraphtext support for web
ChildMindInstitute/mindlogger-web-refactor pull request #512
Opened 2024-07-23 22:37 UTC by ramirlm

- [ ] Tests for the changes have been added
- [ ] Related documentation has been added / updated
- [ ] OSS packages added to MindLogger [open source credit page](https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)

### 📝 Description

🔗 [Jira Ticket M2-7242](https://mindlogger.atlassian.net/browse/M2-7242)

Adds support to `paragraphText` item type

### 📸 Screenshots
![CleanShot 2024-07-23 at 19 35 54](https://github.com/user-attachments/assets/bc721c52-3e1f-4b01-9ddb-7d029a86fb07)

### Notes
I'm adding a default 5(min)-10(max) lines for the paragraph input

2024-07-23 23:18 UTC, david-montano-metalab approved these changes
- Tested it locally alongside https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1502 and it works.
- lints and tests are passing.
- code seems concise and following standards

2024-07-24 17:34 UTC, ChaconC commented on src/entities/activity/lib/types/item.ts
> +  config: TextItemConfig;
You're reusing `TextItemConfig` for ParagraphItem but not all values will be available, only `responseRequired` and  `maxResponseLength`. You should add its own `ParagraphItemConfig`

2024-07-24 17:35 UTC, ChaconC commented on src/entities/activity/ui/items/ParagraphTextItem.tsx
> +type TextItemProps = {
```suggestion
type ParagraphItemProps = {
```

2024-07-24 17:39 UTC, ChaconC commented on src/shared/ui/Items/Text/index.tsx
> +  isLarge?: boolean;
minor nit but I think renaming to `isMultiline` would work better instead of `large`, as that could be confused by `size` or a different style

2024-07-25 20:26 UTC, ChaconC commented on src/entities/activity/lib/types/item.ts
> +  responseDataIdentifier: boolean; // default false
these options are not available to `ParagraphItem`

2024-07-29 22:06 UTC, ChaconC commented
I'm not seeing the responses to a `ParagraphItem` on the admin, and upon inspecting the network tab I see there's only 1 item being sent.

![CleanShot 2024-07-29 at 16 06 03](https://github.com/user-attachments/assets/d41bc8f3-da99-4b61-ab8b-7e266cbe1cb8)
![CleanShot 2024-07-29 at 16 04 41](https://github.com/user-attachments/assets/d4fbf116-d46c-466c-bc36-222fa072f1de)

2024-07-29 22:21 UTC, ChaconC requested changes

2024-07-29 22:21 UTC, ChaconC commented on src/entities/activity/ui/items/ParagraphTextItem.tsx
> +      >{`${numCharacters}/${maxResponseLength} characters`}</Box>
please use `useTranslation` hooks for translatable strings

2024-07-29 22:21 UTC, ChaconC commented on src/entities/activity/ui/items/ItemPicker.tsx
> +      );
There's an unsafe assignment warning on this case.
Please add empty line between cases.

2024-07-30 19:50 UTC, ChaconC commented on src/entities/activity/ui/items/ParagraphTextItem.tsx
> +        {`${numCharacters}/${maxResponseLength} ${t('charactersCount')}`}
This should take the number of characters as param, please check a string like `time_to_complete_hm` for an example on how to implement. The value is not always guaranteed to appear at the start of the string.

2024-07-30 22:40 UTC, ChaconC approved these changes
Good work @ramirlm 

Minor comment about the way the character counter is displayed but I'm sure you can fix that before merging.

Be sure to use squash-merge, and please add (M2-7242) to the merge commit message.

2024-07-30 22:40 UTC, ChaconC commented on src/i18n/en/translation.json
> +    "charactersCount": "({{numCharacters}}/{{maxCharacters}}) characters"
Overall this is fine but I noticed this includes the parenthesis as part of the text, which is unexpected

| Figma | Web app |
|-|-|
| ![CleanShot 2024-07-30 at 16 37 10](https://github.com/user-attachments/assets/25353c67-8627-4028-8399-f401a8ef1995)  |  ![CleanShot 2024-07-30 at 16 37 33](https://github.com/user-attachments/assets/25f7d646-1cf0-4c06-86ea-2ea68ae04c98)  |


Hoping you can fix this in both languages and should be good to go

2024-07-30 23:08 UTC, merged