fix: Fixing word break for large description option answers (M2-8267)
ChildMindInstitute/mindlogger-web-refactor pull request #562
Opened 2024-12-17 13:54 UTC by ramirlm

### 📝 Description

🔗 [Jira Ticket M2-8267](https://mindlogger.atlassian.net/browse/M2-8267)

Changes include:

- Small CSS fix to prevent non-word wrap

### 📸 Screenshots

| Before (Optional)                      | After                                 |
| -------------------------------------- | ------------------------------------- |
| ![CleanShot 2024-12-17 at 10 51 48@2x](https://github.com/user-attachments/assets/0dcfe364-b098-4d2d-b578-f9e69a515553) | ![Code 2024-12-17 10 48 36](https://github.com/user-attachments/assets/68dbbeb1-ec05-4d98-bf61-92108e9efea7) |

### 🪤 Peer Testing

On the admin panel:
- Create an applet with an activity with a large Option text item description
- Assign the activity

On the Web:
- Log in and start the activity
- Check if the item breaks the long description correctly(in words).

2024-12-17 18:31 UTC, ChaconC submitted a review, later dismissed
Tested with Single Select and Multi Select 👍

2025-01-09 19:29 UTC, mbanting requested changes

2025-01-09 19:29 UTC, mbanting commented on src/shared/ui/Items/SelectBase/SelectBaseText.tsx
> +        hyphens: 'auto',
This will still allow the browser is automatically break words at appropriate hyphenation points, following whatever rules it chooses. If the intent is to avoid breaking mid-word altogether, then we should use `[manual](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#manual)` or `[none](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#none)` instead.

2025-01-17 04:43 UTC, ChaconC reviewed
Thanks for the rework on this issue @ramirlm. I'm only seeing issues with the 45-character test cases, but this appears to be limited to mobile resolutions and caused by the title component. It might be worth mentioning this in the linked ticket.

![CleanShot 2025-01-16 at 22 39 03](https://github.com/user-attachments/assets/059253ca-b637-4f4c-a75a-bff21ff6728f)

2025-01-20 18:27 UTC, ChaconC approved these changes

2025-01-23 03:17 UTC, mbanting approved these changes

2025-01-23 23:58 UTC, merged