Feature/m2 1275
ChildMindInstitute/mindlogger-web-refactor pull request #67
Opened 2023-04-10 17:03 UTC by moiskillnadne

2023-04-11 14:10 UTC, BamMironov requested changes

2023-04-12 08:57 UTC, moiskillnadne commented on src/entities/activity/ui/items/Radio.tsx
> +  }, [options])
Done

2023-04-12 09:04 UTC, moiskillnadne commented on src/entities/activity/ui/ActivityCardItem.tsx
> +    }
Done

2023-04-12 13:10 UTC, BamMironov approved these changes

2023-04-12 13:21 UTC, merged