feature: DisableOverlay component
ChildMindInstitute/mindlogger-web-refactor pull request #82
Opened 2023-04-29 11:18 UTC by moiskillnadne

2023-05-02 14:19 UTC, BamMironov requested changes

2023-05-02 20:17 UTC, moiskillnadne commented on src/entities/activity/lib/hooks/useActivitiesByIds.ts
> +    const isLoading = queryResults.reduce((acc, item) => {
Done, thank you!

2023-05-02 20:17 UTC, moiskillnadne commented on src/entities/activity/lib/hooks/useActivitiesByIds.ts
> +    }, false)
Done

2023-05-02 20:19 UTC, moiskillnadne commented on src/entities/activity/lib/hooks/useSupportableActivities.ts
> +    return data.filter(x => x) as Array<ActivityDTO>
Data is Array<ActivityDTO | undefined> type but I need get only Array<ActivityDTO>

2023-05-02 20:37 UTC, moiskillnadne commented on src/entities/activity/model/activityBuilder.ts
> +  public checkIsSupportableActivity(activities: ActivityDTO[]): SupportableActivities | null {
Done

2023-05-02 20:41 UTC, moiskillnadne commented on src/entities/activity/model/activityBuilder.ts
> +  }
I think your suggested way will add extra properties and dependencies between modules/hooks.
Extra dependencies make code difficult to read and support

2023-05-03 13:06 UTC, BamMironov approved these changes

2023-05-03 13:07 UTC, merged